name: invaders
version: 0.0.3
author: Timur Ridjanovic <timur.ridjanovic@gmail.com>
description: A game in Dart. The goal is to survive.
homepage: http://ondart.me/
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
